from bs4 import BeautifulSoup
import pandas as pd

# Sample static HTML content (replace this with the actual HTML content)
html_content = """
<div class="dealermap-list-cards"><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Aabenraa</h2> <address class="dealermap-card-address">
                            Langebro 15
                            <br>
                            6200 Aabenraa
                        </address> <a href="https://www.skoda-aabenraa.dk" target="_blank" class="dealermap-card-url">www.skoda-aabenraa.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Aalborg</h2> <address class="dealermap-card-address">
                            Ny Kærvej 47
                            <br>
                            9000 Aalborg
                        </address> <a href="https://www.skoda-aalborg.dk" target="_blank" class="dealermap-card-url">www.skoda-aalborg.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Brøndby</h2> <address class="dealermap-card-address">
                            Vallensbækvej 5-11
                            <br>
                            2605 Brøndby
                        </address> <a href="https://www.skoda-brondby.dk" target="_blank" class="dealermap-card-url">www.skoda-brondby.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Ejby</h2> <address class="dealermap-card-address">
                            Nørregade 144
                            <br>
                            5592 Ejby
                        </address> <a href="https://www.skoda-ejby.dk" target="_blank" class="dealermap-card-url">www.skoda-ejby.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Esbjerg</h2> <address class="dealermap-card-address">
                            Skagerrakvej 4
                            <br>
                            6715 Esbjerg N
                        </address> <a href="https://www.skoda-esbjerg.dk" target="_blank" class="dealermap-card-url">www.skoda-esbjerg.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Fredericia</h2> <address class="dealermap-card-address">
                            Vesterballevej 9 B
                            <br>
                            7000 Fredericia
                        </address> <a href="https://www.skoda-fredericia.dk" target="_blank" class="dealermap-card-url">www.skoda-fredericia.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Frederikshavn</h2> <address class="dealermap-card-address">
                            Søndergade 250
                            <br>
                            9900 Frederikshavn
                        </address> <a href="https://www.skoda-frederikshavn.dk" target="_blank" class="dealermap-card-url">www.skoda-frederikshavn.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Frederikssund</h2> <address class="dealermap-card-address">
                            Korshøj 1
                            <br>
                            3600 Frederikssund
                        </address> <a href="https://www.skoda-frederikssund.dk" target="_blank" class="dealermap-card-url">www.skoda-frederikssund.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Haderslev</h2> <address class="dealermap-card-address">
                            Klintevej 1
                            <br>
                            6100 Haderslev
                        </address> <a href="https://www.skoda-haderslev.dk" target="_blank" class="dealermap-card-url">www.skoda-haderslev.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Helsingør</h2> <address class="dealermap-card-address">
                            Klostermosevej 121
                            <br>
                            3000 Helsingør
                        </address> <a href="https://www.skoda-helsingor.dk" target="_blank" class="dealermap-card-url">www.skoda-helsingor.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Herning</h2> <address class="dealermap-card-address">
                            Hvidkildevej 5
                            <br>
                            7400 Herning
                        </address> <a href="https://www.skoda-herning.dk" target="_blank" class="dealermap-card-url">www.skoda-herning.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Hillerød</h2> <address class="dealermap-card-address">
                            Egespurs Allé 1
                            <br>
                            3400 Hillerød
                        </address> <a href="https://www.skoda-hilleroed.dk" target="_blank" class="dealermap-card-url">www.skoda-hilleroed.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Hjørring</h2> <address class="dealermap-card-address">
                            Frederikshavnsvej 255
                            <br>
                            9800 Hjørring
                        </address> <a href="https://www.skoda-hjorring.dk" target="_blank" class="dealermap-card-url">www.skoda-hjorring.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Hobro</h2> <address class="dealermap-card-address">
                            Erhvervsparken 6
                            <br>
                            9500 Hobro
                        </address> <a href="https://www.skoda-hobro.dk" target="_blank" class="dealermap-card-url">www.skoda-hobro.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Holbæk</h2> <address class="dealermap-card-address">
                            Bilbyen 1
                            <br>
                            4300 Holbæk
                        </address> <a href="https://www.skoda-holbaek.dk" target="_blank" class="dealermap-card-url">www.skoda-holbaek.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Holstebro</h2> <address class="dealermap-card-address">
                            Nybovej 25
                            <br>
                            7500 Holstebro
                        </address> <a href="https://www.skoda-holstebro.dk" target="_blank" class="dealermap-card-url">www.skoda-holstebro.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Horsens</h2> <address class="dealermap-card-address">
                            Vejlevej 151
                            <br>
                            8700 Horsens
                        </address> <a href="https://www.skoda-horsens.dk" target="_blank" class="dealermap-card-url">www.skoda-horsens.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Højbjerg</h2> <address class="dealermap-card-address">
                            Øster Parkvej 12-16
                            <br>
                            8270 Højbjerg
                        </address> <a href="https://www.skoda-hoejbjerg.dk" target="_blank" class="dealermap-card-url">www.skoda-hoejbjerg.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Kalundborg</h2> <address class="dealermap-card-address">
                            Slagelsevej 162
                            <br>
                            4400 Kalundborg
                        </address> <a href="https://www.skoda-kalundborg.dk" target="_blank" class="dealermap-card-url">www.skoda-kalundborg.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Amager</h2> <address class="dealermap-card-address">
                            Englandsvej 437
                            <br>
                            2770 Kastrup
                        </address> <a href="https://www.skoda-amager.dk" target="_blank" class="dealermap-card-url">www.skoda-amager.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Kolding</h2> <address class="dealermap-card-address">
                            Egtved Allé 1
                            <br>
                            6000 Kolding
                        </address> <a href="https://www.skoda-kolding.dk" target="_blank" class="dealermap-card-url">www.skoda-kolding.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda København</h2> <address class="dealermap-card-address">
                            Banevingen 9
                            <br>
                            2200 København N
                        </address> <a href="https://www.skoda-kbhn.dk" target="_blank" class="dealermap-card-url">www.skoda-kbhn.dk</a> <div class="dealermap-card-labels"><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Køge</h2> <address class="dealermap-card-address">
                            Tangmosevej 110
                            <br>
                            4600 Køge
                        </address> <a href="https://www.skoda-koege.dk" target="_blank" class="dealermap-card-url">www.skoda-koege.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Nykøbing Falster</h2> <address class="dealermap-card-address">
                            Herningvej 24
                            <br>
                            4800 Nykøbing Falster
                        </address> <a href="https://www.skoda-nykf.dk" target="_blank" class="dealermap-card-url">www.skoda-nykf.dk</a> <div class="dealermap-card-labels"><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Næstved</h2> <address class="dealermap-card-address">
                            Bassinbuen 24
                            <br>
                            4700 Næstved
                        </address> <a href="https://www.skoda-naestved.dk" target="_blank" class="dealermap-card-url">www.skoda-naestved.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Nørresundby</h2> <address class="dealermap-card-address">
                            Hjørringvej 142
                            <br>
                            9400 Nørresundby
                        </address> <a href="https://www.skoda-norresundby.dk" target="_blank" class="dealermap-card-url">www.skoda-norresundby.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Odense</h2> <address class="dealermap-card-address">
                            Middelfartvej 50
                            <br>
                            5200 Odense V
                        </address> <a href="https://www.skoda-odense.dk" target="_blank" class="dealermap-card-url">www.skoda-odense.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Randers</h2> <address class="dealermap-card-address">
                            Grenåvej 36
                            <br>
                            8960 Randers SØ
                        </address> <a href="https://www.skoda-randers.dk" target="_blank" class="dealermap-card-url">www.skoda-randers.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Ribe</h2> <address class="dealermap-card-address">
                            Industrivej 5A
                            <br>
                            6760 Ribe
                        </address> <a href="https://www.skoda-ribe.dk" target="_blank" class="dealermap-card-url">www.skoda-ribe.dk</a> <div class="dealermap-card-labels"><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Ringsted</h2> <address class="dealermap-card-address">
                            Bragesvej 1
                            <br>
                            4100 Ringsted
                        </address> <a href="https://www.skoda-ringsted.dk" target="_blank" class="dealermap-card-url">www.skoda-ringsted.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Risskov</h2> <address class="dealermap-card-address">
                            Ravnsøvej 5
                            <br>
                            8240 Risskov
                        </address> <a href="https://www.skoda-risskov.dk" target="_blank" class="dealermap-card-url">www.skoda-risskov.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Roskilde</h2> <address class="dealermap-card-address">
                            Københavnsvej 190
                            <br>
                            4000 Roskilde
                        </address> <a href="https://www.skoda-roskilde.dk" target="_blank" class="dealermap-card-url">www.skoda-roskilde.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Silkeborg</h2> <address class="dealermap-card-address">
                            Lillehøjvej 44
                            <br>
                            8600 Silkeborg
                        </address> <a href="https://www.skoda-silkeborg.dk" target="_blank" class="dealermap-card-url">www.skoda-silkeborg.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Skanderborg</h2> <address class="dealermap-card-address">
                            Dronning Sophies Alle 110
                            <br>
                            8660 Skanderborg
                        </address> <a href="https://www.skoda-skanderborg.dk" target="_blank" class="dealermap-card-url">www.skoda-skanderborg.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Skive</h2> <address class="dealermap-card-address">
                            Katkjærvej 10
                            <br>
                            7800 Skive
                        </address> <a href="https://www.skoda-skive.dk" target="_blank" class="dealermap-card-url">www.skoda-skive.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Slagelse</h2> <address class="dealermap-card-address">
                            Teknikvej 2C
                            <br>
                            4200 Slagelse
                        </address> <a href="https://www.skoda-slagelse.dk" target="_blank" class="dealermap-card-url">www.skoda-slagelse.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Svendborg</h2> <address class="dealermap-card-address">
                            Englandsvej 1
                            <br>
                            5700 Svendborg
                        </address> <a href="https://www.skoda-svendborg.dk" target="_blank" class="dealermap-card-url">www.skoda-svendborg.dk</a> <div class="dealermap-card-labels"><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Next Mobility Svendborg</h2> <address class="dealermap-card-address">
                            Englandsvej 1
                            <br>
                            5700 Svendborg
                        </address> <a href="https://" target="_blank" class="dealermap-card-url"></a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Gladsaxe</h2> <address class="dealermap-card-address">
                            Dynamovej 5
                            <br>
                            2860 Søborg
                        </address> <a href="https://www.skoda-gladsaxe.dk" target="_blank" class="dealermap-card-url">www.skoda-gladsaxe.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Sønderborg</h2> <address class="dealermap-card-address">
                            Alsgade 60-62
                            <br>
                            6400 Sønderborg
                        </address> <a href="https://www.skoda-sonderborg.dk" target="_blank" class="dealermap-card-url">www.skoda-sonderborg.dk</a> <div class="dealermap-card-labels"><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Thisted</h2> <address class="dealermap-card-address">
                            Uglevej 1
                            <br>
                            7700 Thisted
                        </address> <a href="https://www.skoda-thisted.dk" target="_blank" class="dealermap-card-url">www.skoda-thisted.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Tønder</h2> <address class="dealermap-card-address">
                            Ribelandevej 55
                            <br>
                            6270 Tønder
                        </address> <a href="https://www.skoda-tonder.dk" target="_blank" class="dealermap-card-url">www.skoda-tonder.dk</a> <div class="dealermap-card-labels"><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Vejle</h2> <address class="dealermap-card-address">
                            Bugattivej 4
                            <br>
                            7100 Vejle
                        </address> <a href="https://www.skoda-vejle.dk" target="_blank" class="dealermap-card-url">www.skoda-vejle.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Viborg</h2> <address class="dealermap-card-address">
                            Lundborgvej 12
                            <br>
                            8800 Viborg
                        </address> <a href="https://www.skoda-viborg.dk" target="_blank" class="dealermap-card-url">www.skoda-viborg.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div><div role="button" class="dealermap-card card"><h2 class="dealermap-card-title headline-6">Škoda Virum</h2> <address class="dealermap-card-address">
                            Grønnevej 134-138
                            <br>
                            2830 Virum
                        </address> <a href="https://www.skoda-virum.dk" target="_blank" class="dealermap-card-url">www.skoda-virum.dk</a> <div class="dealermap-card-labels"><div class="dealermap-card-label"><svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-md-vehicle-front"></use></svg> <!----> <span>Forhandler</span></div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div class="dealermap-card-label"><!----> <svg focusable="false" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/ui/dist/icons/custom-sprite.svg#icon-tools"></use></svg> <span>Servicepartner</span></div></div></div></div>
"""

# Parse the HTML content
soup = BeautifulSoup(html_content, 'html.parser')

# Find all dealer cards
dealer_cards = soup.find_all("div", class_="dealermap-card")

# Initialize empty lists to store data
names = []
addresses = []
websites = []
labels = []

# Extract information from each dealer card
for card in dealer_cards:
    name = card.find("h2", class_="dealermap-card-title").text.strip()
    address = card.find("address", class_="dealermap-card-address").get_text("\n", strip=True)
    website = card.find("a", class_="dealermap-card-url")['href']
    label = card.find("div", class_="dealermap-card-label").span.text.strip()

    names.append(name)
    addresses.append(address)
    websites.append(website)
    labels.append(label)

# Create a DataFrame
data = {
    "Name": names,
    "Address": addresses,
    "Website": websites,
    "Label": labels
}
df = pd.DataFrame(data)

# Save the data to an Excel file
df.to_excel("skoda_dealers.xlsx", index=False)
